apps/shop/urls.py
from django.urls import path

from apps.shop.views import (
    ProductsView, ProductAddFormView, ProductDeleteView, BoughtProductsView,
    CollectionView, ProductOwnerView, ShopOwnerView, add_collection_with_ajax
)


urlpatterns = [
    path('products/', ProductsView.as_view(), name='products'),
    path('add/', ProductAddFormView.as_view(), name='product-add'),
    path('add_collection/', add_collection_with_ajax, name='collection-add'),
    path('delete/<slug:slug>/', ProductDeleteView.as_view(), name='product-delete'),
    path('bought-products/', BoughtProductsView.as_view(), name='bought-products'),
    path('collection/', CollectionView.as_view(), name='collection'),
    path('<slug:shop_owner>/', ShopOwnerView.as_view(), name='shop-owner'),
    path('<slug:shop_owner>/<slug:product_owner>/', ProductOwnerView.as_view(), name='product-owner'),
]

core/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('apps.users.urls')),
    path('', include('apps.taplink.urls')),
    path('customer/', include('apps.customer.urls')),
    path('', include('apps.shop.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from apps.shop.utils import image_upload_to, create_unique_slug
from apps.taplink.models import TapLink


CustomUser = get_user_model()


class Product(models.Model):
    """Model for creating a Product object."""
    name = models.CharField(max_length=120, verbose_name='Название')
    slug = models.SlugField(max_length=120, unique=True)
    description = models.TextField(
        null=True, blank=True, verbose_name='Описание'
    )
    collections = models.ManyToManyField(
        to='Collection', related_name='products', verbose_name='Коллекции'
    )
    old_price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Старая цена'
    )
    current_price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Новая цена'
    )
    quantity = models.PositiveIntegerField(verbose_name='Количество')
    is_available = models.BooleanField(default=True, verbose_name='В наличии')
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания'
    )
    owner = models.ForeignKey(
        to=TapLink, on_delete=models.CASCADE, related_name='products',
        verbose_name='Владелец'
    )

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        """Return product by the name."""
        return self.name

    def save(self, *args, **kwargs):
        """Save the current instance with a unique slug."""
        if not self.slug:
            self.slug = create_unique_slug(Product, self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url_for_owner(self):
        """Return URL for a given object over HTTP."""
        return reverse(
            'product-owner',
            kwargs={
                'shop_owner': self.owner.pathname,
                'product_owner': self.slug
            }
        )

    def get_absolute_url_for_customer(self):
        """Return URL for a given object over HTTP."""
        return reverse(
            'product-customer',
            kwargs={
                'shop_customer': self.owner.pathname,
                'product_customer': self.slug
            }
        )


class Collection(models.Model):
    """Model for creating a Collection object."""
    name = models.CharField(
        max_length=200, unique=True, verbose_name='Название'
    )
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        verbose_name = 'Коллекция'
        verbose_name_plural = 'Коллекции'

    def __str__(self):
        """Return collection by the name."""
        return self.name

    def save(self, *args, **kwargs):
        """Save the current instance with a unique slug."""
        if not self.slug:
            self.slug = create_unique_slug(Collection, self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Return URL for a given object over HTTP."""
        return reverse('collection_page', kwargs={'slug': self.slug})


class ProductImage(models.Model):
    """Model for creating an Image object for Product model."""
    image = models.ImageField(
        upload_to=image_upload_to, verbose_name='Изображение'
    )
    product = models.ForeignKey(
        to=Product, on_delete=models.CASCADE, related_name='images',
        verbose_name='Товар'
    )

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def __str__(self):
        """Return images by product's name."""
        return self.product.name

    def get_absolute_url(self):
        """Return URL for a given object over HTTP."""
        return reverse('shop-inner', kwargs={'slug': self.product.slug})

apps/shop/forms.py
from django import forms

from .models import Product, ProductImage


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'name', 'description', 'old_price', 'current_price', 'quantity',
            'is_available'
        )


class ProductImageForm(forms.ModelForm):
    image = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = ProductImage
        fields = ('image',)

apps/shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, DetailView, DeleteView

from apps.customer.models import OrderItem
from apps.shop.forms import ProductForm, ProductImageForm
from apps.shop.models import Product, ProductImage, Collection
from apps.taplink.models import TapLink


class ProductsView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'pages/shop/products.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):
        if self.request.GET.get('search'):
            return Product.objects.filter(
                Q(name__icontains=self.request.GET.get('search')) &
                Q(owner__user=self.request.user) &
                Q(is_available=True)
            ).prefetch_related('collections')
        else:
            return Product.objects.filter(
                Q(owner__user=self.request.user) &
                Q(is_available=True)
            ).prefetch_related('collections')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_form'] = ProductForm
        context['image_form'] = ProductImageForm
        context['collections'] = Collection.objects.filter(
            products__owner__user=self.request.user
        ).distinct()
        context['pathname'] = TapLink.objects.get(
            user=self.request.user
        ).pathname
        return context


class ProductAddFormView(LoginRequiredMixin, FormView):
    template_name = 'pages/shop/products.html'
    form_class = ProductForm

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = TapLink.objects.get(user=self.request.user)
        product.save()
        for image in self.request.FILES.getlist('images'):
            ProductImage.objects.create(image=image, product=product)
        product.collections.set(list(Collection.objects.filter(
            name__in=form.data['collections'].split(',')))
        )
        return redirect('products')


def add_collection_with_ajax(request):
    if request.method == 'POST':
        collection = Collection()
        collection.name = request.POST.get('collectionValue')
        collection.save()
    return render(request, 'pages/shop/products.html')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'pages/shop/products.html'
    success_url = reverse_lazy('products')


class BoughtProductsView(LoginRequiredMixin, ListView):
    model = OrderItem
    template_name = 'pages/shop/bought-products.html'
    context_object_name = 'ordered_items'
    paginate_by = 8
    queryset = OrderItem.objects.select_related('order', 'product')


class CollectionView(LoginRequiredMixin, ListView):
    model = Collection
    template_name = 'pages/shop/collection.html'
    context_object_name = 'collections'

    def get_queryset(self):
        return Collection.objects.filter(
            products__owner__user=self.request.user
        ).annotate(products_per_collection=Count('products'))


class ProductOwnerView(DetailView):
    model = Product
    template_name = 'pages/shop/product-owner.html'
    context_object_name = 'product'
    slug_url_kwarg = 'product_owner'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['images'] = ProductImage.objects.filter(product=self.object)
        return context


class ShopOwnerView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'pages/shop/shop-owner.html'
    context_object_name = 'products'

    def get_queryset(self):
        if self.request.GET.get('search'):
            return Product.objects.filter(
                Q(name__icontains=self.request.GET.get('search')) &
                Q(owner__user=self.request.user) &
                Q(is_available=True)
            ).prefetch_related('images').select_related('owner')
        else:
            return Product.objects.filter(
                Q(owner__user=self.request.user) &
                Q(is_available=True)
            ).prefetch_related('images').select_related('owner')

templates/pages/change-number.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form action="" id="number" data-url="{% url 'val-number_page' %}" style="display: block;">
                <div class="form__box-head">
                    <h2 class="form__title">
                        Введите новый номер
                    </h2>
                </div>
                <label class="form__input-wrap">
                    <input type="text" id="input_number" class="form__input form__input-tel" required>
                </label>
                <button onclick="validateNumber()" class="form__btn" type="button">
                    Сохранить изменения
                </button>
                <button id='sign-in-button' hidden></button>
            </form>

            <form action="{% url 'change-num_page' %}" id="submit" style="display: none;" method="post">
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Подтверждение номера
                        телефона
                    </h2>
                </div>
                <div class="check__number">
                    <div class="profile__icon">
                        <svg width="40" height="41" viewBox="0 0 40 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M36.0994 36.4314C35.1498 33.7735 33.0574 31.4248 30.1467 29.7497C27.2359 28.0746 23.6696 27.1666 20.0007 27.1666C16.3318 27.1666 12.7654 28.0746 9.85463 29.7497C6.94389 31.4248 4.85147 33.7735 3.90189 36.4314"
                                  stroke="#979797" stroke-width="3" stroke-linecap="round"/>
                            <ellipse cx="19.9993" cy="13.8333" rx="8.33333" ry="8.33333" stroke="#979797"
                                     stroke-width="3" stroke-linecap="round"/>
                        </svg>
                    </div>
                    <div>
                        <p class="check__number-number">
                            +996 700 12 34 56
                        </p>
                        <a href="{% url 'change-num_page' %}" class="wrong__number">
                            Неверный номер телефона?
                        </a>
                    </div>
                </div>
                <label class="form__input-wrap">
                    <input type="hidden" id="phone_number" name="phone_number" class="form__input" required>
                </label>
                <label class="form__input-wrap">
                    <input type="text" id="input_code" class="form__input" placeholder="Введите код подтверждения" required>
                </label>
                <button onclick="sendConfirmCode()" id="send_code" class="form__btn" type="button">
                    Подтвердить
                </button>
                <a href="" class="no__sms">
                    Не пришло SMS сообщение?
                </a>
                <button onclick="getConfirmCode()" id="get_code" class="sms__timer" type="button" disabled>
                    Отправить снова через 0:<span class="timer__seconds">59</span>
                </button>
                <button id="submit-messenger" type="submit" hidden></button>
                <button id='sign-in-button' hidden></button>
            </form>
        </div>
    </div>

    <div class="success__notification">
        Номер успешно изменен
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/change-number.js' %}"></script>
    <script src="{% static 'js/intl-tel-input-mask__custom-f/js/settings-mask.js' %}"></script>
{% endblock %}

templates/pages/change-password-done.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}
    <div class="success__notification">
        Пароль успешно изменен
    </div>
{% endblock %}

{% block scripts %}{% endblock %}

templates/pages/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}
    <div class="box__wrap">
        <div class="form__box">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Придумайте новый пароль
                    </h2>
                </div>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" name="old_password" class="form__input" placeholder="Введите старый пароль" required>
                    <div class="form__eye"></div>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" name="new_password1" class="form__input" placeholder="Придумайте новый пароль" required>
                    <div class="form__eye"></div>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" name="new_password2" class="form__input" placeholder="Повторите пароль" required>
                    <div class="form__eye"></div>
                </label>
                <button class="form__btn" type="submit">
                    Сохранить изменения
                </button>
            </form>
        </div>
    </div>
    <div class="success__notification">
        Пароль успешно изменен
    </div>
{% endblock %}

{% block scripts %}{% endblock %}

templates/pages/edit-profile.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Профиль
                    </h2>
                    <a href="{% url 'log-out' %}" class="form__reg form__sign-out">
                        Выход
                    </a>
                </div>
                <label class="form__input-wrap">
                    <input type="text" name="first_name" class="form__input" value="{{ user.first_name }}" placeholder="Введите новое имя" required>
                </label>
                <label class="form__input-wrap">
                    <input type="text" name="last_name" class="form__input" value="{{ user.last_name }}" placeholder="Введите новую фамилию" required>
                </label>
                <button class="form__btn" type="submit">
                    Сохранить изменения
                </button>
                <a href="{% url 'change-password_page' %}" class="sms__timer change__filed">
                    Сменить пароль
                </a>
                <a href="{% url 'change-num_page' %}" class="sms__timer change__filed">
                    Сменить номер
                </a>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}{% endblock %}

templates/pages/products.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}
    <div class="products-header-wrap">
        <div class="container">
            <div class="products-header">
                <!--        активным link добавить класс active-->
                {% include 'components/subnavs.html' %}
                <div class="link add-new-prod" data-micromodal-trigger="add-product">Добавить новый товар</div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="prod-content">
            <div class="prod-content-header">
                <form action="" class="search">
                    <input name="search" type="text" class="search-input" placeholder="Поиск">
                    <button type="submit" class="search-btn"></button>
                </form>
                <div class="pagination-wrap">
                    {% include 'components/pagination.html' %}
                </div>
            </div>
            <div class="prod-table-wrap">
                <table class="prod-table">
                    <tr>
                        <th>
                            <div>Название</div>
                        </th>
                        <th>
                            <div>Цена</div>
                        </th>
                        <th>
                            <div>Дата добавления</div>
                        </th>
                        <th>
                            <div>Количество товара</div>
                        </th>
                        <th>
                            <div>Коллекция</div>
                        </th>
                    </tr>
                    {% for product in products %}
                        <tr>
                            <td>{{ product.name }}</td>
                            <td><span class="old-price">{{ product.old_price }}</span><span>{{ product.current_price }}</span></td>
                            <td>{{ product.created|date:'d.m.y' }}</td>
                            <td>{{ product.quantity }} шт.</td>
                            <td>
                                <div class="tags">
                                    <div class="tags-flex">
                                        {% for collection in product.collections.all %}
                                            <div class="tag-item">{{ collection.name }}</div>
                                        {% endfor %}
                                    </div>
                                    <div class="delete">
                                        <form action="{% url 'product-delete' product.slug %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit">Удалить</button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <div class="modal micromodal-slide" id="add-product" aria-hidden="true">
        <div class="modal__overlay" tabindex="-1" data-micromodal-close>
            <div class="modal__container add-product" role="dialog" aria-modal="true"
                 aria-labelledby="modal-title">
                <form action="{% url 'product-add' %}" id="add" data-url="{% url 'collection-add' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="controll__block add-modal">
                        <div class="controll__block-head">
                            <h5>Добавить товар</h5>
                            <div class="controll__block-close" aria-label="Close modal"
                                 data-micromodal-close>
                            </div>
                        </div>
                        {#                                                {{ images_form.as_p }}#}
                        <input name="name" type="text" class="controll__input"
                               placeholder="Название товара">
                        <textarea name="description" class="controll__input add-textarea" placeholder="Описание товара"></textarea>
                        <input name="collections" id="id_collections" type="hidden" class="controll__input"
                               placeholder="Hidden collections">
                        <div class="collection">
                            <div class="collection-tags">
                                {% for collection in collections %}
                                    <div class="collection-item">{{ collection.name }}</div>
                                {% endfor %}
                            </div>
                            <div class="add-collection-wrap">
                                <div class="add-collection">Новая коллекция</div>
                            </div>
                        </div>
                        <div class="new-collection">
                            <input type="text" id="add_collection" class="controll__input new-coll-input"
                                   placeholder="Название новой коллекции">
                            <div id="submit_collection" class="add-prod-btn add-new-coll">Добавить</div>
                        </div>
                        <div class="price-inputs">
                            <input name="old_price" type="text" class="controll__input"
                                   placeholder="Старая цена">
                            <input name="current_price" type="text" class="controll__input"
                                   placeholder="Новая цена">
                        </div>
                        <input name="quantity" type="text" class="controll__input"
                               placeholder="Количество товара">
                        <br>
                        <input name="is_available" id="id_is_available" type="hidden" class="controll__input"
                               placeholder="Hidden boolean">
                        <div class="add-photo-head">
                            <span>Виден в каталоге:</span>
                            <div class="catalog-toggle">
                                <span>Да</span>
                                <span>Нет</span>
                            </div>
                        </div>
                        <div class="add-photo">
                            <div class="add-photo-item add-drop">
                                <img src="{% static 'img/icon/camera.svg' %}" alt="">
                                <span>Добавить</span>
                                <input name="images" multiple id="add-photo" type="file">
                            </div>
                        </div>
                        <button type="submit" class="add-prod-btn">Добавить товар</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $('.add-textarea').on('input', function () {
            this.style.height = "";
            this.style.height = this.scrollHeight + "px";
        })

        let defaultBoolean = 'True'

        $('#id_is_available').val(defaultBoolean)

        $('.catalog-toggle').on('click', function () {
            $(this).toggleClass('hide')
            if ($(this).hasClass('hide')){
                $('#id_is_available').val('False')
            }else{
                $('#id_is_available').val('True')
            }
        })

        $('.add-collection').on('click', function () {
            $('.new-collection').addClass('show')
        })

        let arrayCollection = []

        $('.collection-item').on('click', function () {
            $(this).toggleClass('active')
            if ($(this).hasClass('active')){
                arrayCollection.push($(this).text())
            }

            $('#id_collections').val(arrayCollection.map(c => c))

        })

        $('.add-new-coll').on('click', function () {
            let collectionField = $('.new-coll-input')

            $('#id_collections').val(collectionField.val())

            if(collectionField.val() !== '') {
                $('.collection-tags').append($('<div class="collection-item">'+ collectionField.val() + '</div>'))
                arrayCollection.push(collectionField.val())
                $('#id_collections').val(arrayCollection.map(c => c))
            }
        })

        $(document).ready(function () {
            $('#submit_collection').on('click', function () {
                $.ajax({
                    method:'POST',
                    url: $("#add").attr("data-url"),
                    data:{
                        collectionValue: $('#add_collection').val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function() {
                        alert('Collection successfully posted');
                    },
                });
                $('#add_collection').val('')
            });
        });
    </script>
    <script>
        $(document).ready(function () {

            let readURL = function (input) {
                if (input.files && input.files[0]) {
                    let reader = new FileReader();

                    reader.onload = function (e) {
                        $('.add-photo').append('<div class="add-photo-item">' +
                            '<div class="delete"></div>' +
                            '<img class="product-img" src="'+ e.target.result +'" alt="">' +
                            '</div>')
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#add-photo").on('change', function () {
                readURL(this);
            });

            $(document).on('click', '.add-photo-item .delete', function () {
                $(this).parent().remove()
            })

        });
    </script>
{% endblock %}

templates/pages/registration-number.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form action="" id="number" data-url="{% url 'val-number_page' %}" style="display: block;">
                <div class="form__box-head">
                    <h2 class="form__title">
                        Для продолжения, введите номер телефона
                    </h2>
                </div>
                <label class="form__input-wrap">
                    <input type="text" id="input_number" class="form__input form__input-tel" required>
                </label>
                <button onclick="validateNumber()" id="disable_button" class="form__btn" type="button">
                    Отправить код
                </button>
                <button id='sign-in-button' hidden></button>
            </form>

            <form action="" id="submit" data-url="{% url 'reg_page' %}" style="display: none;">
                <div class="form__box-head">
                    <h2 class="form__title">
                        Подтверждение номера
                        телефона
                    </h2>
                </div>
                <div class="check__number">
                    <div class="profile__icon">
                        <svg width="40" height="41" viewBox="0 0 40 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M36.0994 36.4314C35.1498 33.7735 33.0574 31.4248 30.1467 29.7497C27.2359 28.0746 23.6696 27.1666 20.0007 27.1666C16.3318 27.1666 12.7654 28.0746 9.85463 29.7497C6.94389 31.4248 4.85147 33.7735 3.90189 36.4314"
                                  stroke="#979797" stroke-width="3" stroke-linecap="round"/>
                            <ellipse cx="19.9993" cy="13.8333" rx="8.33333" ry="8.33333" stroke="#979797"
                                     stroke-width="3" stroke-linecap="round"/>
                        </svg>
                    </div>
                    <div>
                        <p class="check__number-number">
                            +996 700 12 34 56
                        </p>
                        <a href="{% url 'reg-number_page' %}" class="wrong__number">
                            Неверный номер телефона?
                        </a>
                    </div>
                </div>
                <label class="form__input-wrap">
                    <input type="text" id="input_code" class="form__input" placeholder="Введите код подтверждения" required>
                </label>
                <button onclick="sendConfirmCode()" id="send_code" class="form__btn" type="button">
                    Отправить код
                </button>
                <a href="" class="no__sms">
                    Не пришло SMS сообщение?
                </a>
                <button onclick="getConfirmCode()" id="get_code" class="sms__timer" type="button" disabled>
                    Отправить снова через 0:<span class="timer__seconds">59</span>
                </button>
                <button id='sign-in-button' hidden></button>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/registration-number.js' %}"></script>
    <script src="{% static 'js/intl-tel-input-mask__custom-f/js/settings-mask.js' %}"></script>
{% endblock %}